### ISSUE TITLE
Mabe use FST

### ISSUE THREAD

**Issue by Eh2406** [gregstoll/wheeloffortune#1]
If you are running regexs against a long static list of strings, then you may want to look into the FST crate. And the [blog post](https://blog.burntsushi.net/transducers/) announcing it is worth the read even if it does not work out.

**Comment by gregstoll** [comment]
Oh, this looks interesting - going to set aside some time to read this. Thanks!

**Comment by gregstoll** [comment]
Yup, this was a big win if there aren't too many question marks. (see the benchmarks in the linked PR) Thanks so much for the suggestion!
